language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - extra-google-m2repository
    - extra-android-m2repository
    - build-tools-25.0.0
    - android-16