language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-26

os: linux

branches:
  except:
    - docs-review
    - master-readme-review
