matrix:
  include:
  - language: java
        sudo: false
            jdk:
              - openjdk7

  - language: android
    jdk: oraclejdk8
    android:
      components:
        - tools
        - android-21
        - build-tools-25.0.3
